### PR TITLE
xml files changed

### PR DESCRIPTION
**Pull request by udayaKavinda**
all primary colors and resource files updated,redundant dependencies removed.

### CODE REVIEW

**Comment by EshanJayasundara** [comment]
What were the redundant dependencies that u have removed.

**Comment by udayaKavinda** [comment]
firebse database.

**Comment by EshanJayasundara** [comment]
dont remove remove the database connection.....

**Comment by udayaKavinda** [comment]
i removed firebase databse only not firestore.no any issue.works fine

**Comment by EshanJayasundara** [comment]
ok bro the I'll merge after my own verification ok..

**Comment by EshanJayasundara** [comment]
It seems like working fine.

**Comment by EshanJayasundara** [comment]
I have merged with all ur updates.

**Pull request merged**
